export const RMQ_SERVICE = 'RMQ_SERVICE';

export const AUTH_SERVICE = 'AUTH_SERVICE';
export const NOTIFICATIONS_EVENTS_CLIENT = 'NOTIFICATIONS_EVENTS_CLIENT';
export const AUTHZ_EVENTS_CLIENT = 'AUTHZ_EVENTS_CLIENT';
